### ISSUE TITLE
Label is on the wrong position

### ISSUE THREAD

**Issue by Phoenix-flame** [Kljunas2/activate-linux#1]
Text label is on the top left side of screen instead of bottom right !
I'm not familiar with gtk, but i'm curious about this little fun project  :)

**Comment by Kljunas2** [comment]
I'm not sure why. When I run it, the label is in the bottom right corner. Also, the code seems correct to me: https://github.com/Kljunas2/activate-linux/blob/aed9443796bc30bb6d7bf78354811f61483f04f4/src/activate_linux.c#L18-L23

**Comment by Kljunas2** [comment]
Are you running on Gnome. That might be the problem, since Gnome compositor does not support layer shell.

**Comment by Phoenix-flame** [comment]
You are right, it's kinda a problem with my desktop manager
