### ISSUE TITLE
Wrong position and visibility

### ISSUE THREAD

**Issue by JustCryen** [Kljunas2/activate-linux#10]
It appeared on the top left side and it is being displayed under the programs, not over.
Another problem is that it is visible when in overview, it is listed alongside other apps.

OS: Archlinux
DE: Gnome 42.2

**Comment by Kljunas2** [comment]
This is Gnome's problem, since it does not support layer shell protocol.

**Comment by JustCryen** [comment]
Ah, gotcha.
On the other hand Xorg version is working great.
