### ISSUE TITLE
Doesn't render on top of full screen opengl games

### ISSUE THREAD

**Issue by Mart-Bogdan** [Kljunas2/activate-linux#12]
I've tried it with Starsector, and it didn't work. Which uses OpenGL

I haven't tried it with Vulkan games and with windowed fullscreen mode.

Compatitor https://github.com/MrGlockenspiel/activate-linux actually works on top of fulls screen games.

**Comment by Kljunas2** [comment]
Sorry for this unprofessional bug.

**Comment by Mart-Bogdan** [comment]
WOW! That was fast fix! Thank you. It really works now.

**P.S.** Your version has nice choice of color, it's clearly visible on top of white windows :-)

**Comment by Mart-Bogdan** [comment]
Now can enjoy it on Github site and over Signal as well.
