### ISSUE TITLE
Stuck in a "App not responding" loop

### ISSUE THREAD

**Issue by mthw0** [Kljunas2/activate-linux#5]
Using Gnome 42, every few seconds there is a message about app "Unknown" is not responding wait or force quit? I installed latest version from AUR. Any other info I should provide?

**Comment by Kljunas2** [comment]
Apparently layer shell is [not supported on Gnome](https://github.com/wmww/gtk-layer-shell#supported-desktops). Does the window show, or are you getting oly the message?

**Comment by mthw0** [comment]
It does show in top left corner (already reported) and one can also Alt-tab into the app (another issue?).

**Comment by Kljunas2** [comment]
I think that is the problem with Gnome wayland compositor not impementing xdg layer shell protocol, so Gtk Layer Shell opens regular window instead.
