### ISSUE TITLE
Can not click

### ISSUE THREAD

**Issue by Zhou-Yicheng** [Kljunas2/activate-linux#8]
I can not click something (like a link) behind the watermark, is it a bug?

**Comment by Kljunas2** [comment]
What is the behaviour on Windows?

**Comment by Kljunas2** [comment]
It seems to be hard to fix. To allow pointer clicks to pass the surface [input region should be changed.](https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:request:set_keyboard_interactivity) But I haven't yet found a way to change it. It may [even be impossible](https://github.com/wmww/gtk-layer-shell/issues/30).

**Comment by Zhou-Yicheng** [comment]
> What is the behaviour on Windows?

not know




> It may [even be impossible](https://github.com/wmww/gtk-layer-shell/issues/30).

ah oh
